server:
  port: 8080

spring:
  application:
    name: api-gateway-dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/auth/realms/amazin

jwt:
  azp: webapp