server:
  port: 8080

basket:
  host: basket-amazin-dev.apps.ocp.datr.eu

inventory:
  host: inventory-amazin-dev.apps.ocp.datr.eu

user:
  host: user-amazin-dev.apps.ocp.datr.eu

spring:
  application:
    name: api-gateway-dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/auth/realms/amazin

jwt:
  azp: webapp