server:
  port: 1080

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  application:
    name: api-gateway-test

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://kc.services.theosmo.com/auth/realms/VRM-DEV

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/auth/realms/amazin

jwt:
  azp: vrm-shell-oidc