server:
  port: 9080

logging:
  level:
    org:
      thymeleaf: INFO
      springframework:
        security: INFO

spring:
  application:
    name: webapp

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: webapp
            client-secret: "cc48f8ad-80d3-4019-8d36-7dfb6f5c86e7"
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            authorization-uri: "http://127.0.0.1:8080/auth/realms/amazin/protocol/openid-connect/auth"
            token-uri: "http://127.0.0.1:8080/auth/realms/amazin/protocol/openid-connect/token"
            user-info-uri: "http://127.0.0.1:8080/auth/realms/amazin/protocol/openid-connect/userinfo"
            userNameAttribute: name
            jwk-set-uri: "http://127.0.0.1:8080/auth/realms/amazin/protocol/openid-connect/certs"


zuul:
  routes:
    products:
      path: /all
      url: http://127.0.0.1:1080/api/products
      stripPrefix: true


