server:
  port: 9080
  servlet:
    session:
      timeout: 1m
  session:
    timeout: 1m

logging:
  level:
    org:
      thymeleaf: INFO
      springframework:
        security: TRACE


spring:
  application:
    name: webapp

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: webapp
            client-secret: "5fd64c9b-a065-46e8-b49b-3203c1ea586e"
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            authorization-uri: "http://127.0.0.1:8080/auth/realms/amazin/protocol/openid-connect/auth"
            token-uri: "http://127.0.0.1:8080/auth/realms/amazin/protocol/openid-connect/token"
            user-info-uri: "http://127.0.0.1:8080/auth/realms/amazin/protocol/openid-connect/userinfo"
            userNameAttribute: name
            jwk-set-uri: "http://127.0.0.1:8080/auth/realms/amazin/protocol/openid-connect/certs"




  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

zuul:
  routes:
    products:
      path: /all
      url: http://127.0.0.1:1080/api/products
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie
  sensitiveHeaders: Cookie,Set-Cookie

